# Generated by Django 5.2.4 on 2025-09-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_phone', models.CharField(max_length=10, unique=True)),
                ('seller_email', models.EmailField(max_length=254, unique=True)),
                ('seller_password', models.CharField(max_length=255, null=True)),
                ('business_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('seller_address', models.TextField()),
                ('seller_pincode', models.CharField(max_length=6)),
                ('business_type', models.CharField(choices=[('proprietorship', 'Proprietorship'), ('partnership', 'Partnership'), ('private_limited', 'Private Limited'), ('llp', 'LLP'), ('individual', 'Individual Seller')], max_length=50)),
                ('selling_category', models.CharField(choices=[('all', 'All Categories'), ('mobile', 'Mobile Phones'), ('watch', 'Watches'), ('laptop', 'Laptop'), ('shoes', 'Shoes'), ('tv', 'Television'), ('earphones', 'Ear Phones'), ('toys', 'Toys'), ('books', 'Books')], default='all', max_length=50)),
                ('gstin', models.CharField(blank=True, help_text='Enter 15-digit GSTIN', max_length=15, null=True)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
