# Generated by Django 5.2.4 on 2025-09-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='addProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('brandName', models.CharField(max_length=200)),
                ('productDescription', models.TextField()),
                ('productHiglight', models.TextField()),
                ('productCategory', models.CharField(choices=[('all', 'All Categories'), ('mobile', 'Mobile Phones'), ('watch', 'Watches'), ('laptop', 'Laptop'), ('shoes', 'Shoes'), ('tv', 'Television'), ('earphones', 'Ear Phones'), ('toys', 'Toys'), ('books', 'Books')], default='all', max_length=50)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discountPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productSellerName', models.CharField(max_length=200)),
                ('productCompanyName', models.CharField(max_length=200)),
                ('companyLocation', models.TextField()),
                ('productImage1', models.ImageField(null=True, upload_to='product_images/')),
                ('productImage2', models.ImageField(null=True, upload_to='product_images/')),
                ('productImage3', models.ImageField(null=True, upload_to='product_images/')),
                ('productAddress', models.CharField(max_length=200)),
                ('productState', models.CharField(max_length=200)),
                ('productCountry', models.CharField(max_length=200)),
                ('productPincode', models.IntegerField()),
            ],
        ),
    ]
