# Generated by Django 5.2.4 on 2025-09-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='companyLocation',
        ),
        migrations.AddField(
            model_name='addproduct',
            name='sellerEmail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='sellerPhone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
