# Generated by Django 5.2.4 on 2025-09-25 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_addproduct_companylocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='productHiglight',
            new_name='productHighlight',
        ),
    ]
