# Generated by Django 5.2.4 on 2025-09-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_producthiglight_addproduct_producthighlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='sellerPhone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
