# Generated by Django 5.2.4 on 2025-09-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_addproduct_sellerphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='sellerEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
