# Generated by Django 5.2.4 on 2025-09-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_mobileproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addProduct',
        ),
    ]
