# Generated by Django 5.2.4 on 2025-09-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_addproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobileproduct',
            old_name='displayResolution',
            new_name='batteryCapacity',
        ),
        migrations.RenameField(
            model_name='mobileproduct',
            old_name='charging',
            new_name='chargingSpeed',
        ),
        migrations.RenameField(
            model_name='mobileproduct',
            old_name='mainCamera',
            new_name='macroLens',
        ),
        migrations.RenameField(
            model_name='mobileproduct',
            old_name='mainCameraFeatures',
            new_name='mainLens',
        ),
        migrations.RenameField(
            model_name='mobileproduct',
            old_name='selfieCameraFeatures',
            new_name='opticalZoom',
        ),
        migrations.RenameField(
            model_name='mobileproduct',
            old_name='sensors',
            new_name='selfieWideCamera',
        ),
        migrations.RemoveField(
            model_name='mobileproduct',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='mobileproduct',
            name='fiveGBands',
        ),
        migrations.RemoveField(
            model_name='mobileproduct',
            name='fourGBands',
        ),
        migrations.RemoveField(
            model_name='mobileproduct',
            name='internalStorage',
        ),
        migrations.RemoveField(
            model_name='mobileproduct',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='mobileproduct',
            name='storageVariants',
        ),
        migrations.RemoveField(
            model_name='mobileproduct',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='mobileproduct',
            name='threeGBands',
        ),
        migrations.RemoveField(
            model_name='mobileproduct',
            name='twoGBands',
        ),
        migrations.AddField(
            model_name='mobileproduct',
            name='displayResolution1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mobileproduct',
            name='displayResolution2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mobileproduct',
            name='fingerPrint',
            field=models.CharField(blank=True, choices=[('none', 'No Fingerprint'), ('rear-mounted', 'Rear-mounted'), ('side-mounted', 'Side-mounted'), ('front-mounted', 'Front-mounted'), ('under-display-optical', 'Under-display (Optical)'), ('under-display-ultrasonic', 'Under-display (Ultrasonic)'), ('power-button', 'Power Button Integrated')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mobileproduct',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mobileproduct',
            name='internalStorageRam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mobileproduct',
            name='internalStorageRom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mobileproduct',
            name='telePhotoLens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileproduct',
            name='thickness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mobileproduct',
            name='wideAngleLens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileproduct',
            name='width',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mobileproduct',
            name='wirelessChargingSpeed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mobileproduct',
            name='cardSlot',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mobileproduct',
            name='mainCameraVideo',
            field=models.CharField(blank=True, choices=[('8k 30fps', '8k 30fps'), ('4k 120fps', '4k 120fps'), ('4k 60fps', '4k 60fps'), ('4k 30fps', '4k 30fps'), ('1080p 120fps', '1080p 120fps'), ('1080p 60fps', '1080p 60fps'), ('1080p 30fps', '1080p 30fps')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mobileproduct',
            name='modelsAvailable',
            field=models.CharField(blank=True, choices=[('6 GB | 64 GB', '6 GB | 64 GB'), ('6 GB | 128 GB', '6 GB | 128 GB'), ('6 GB | 256 GB', '6 GB | 256 GB'), ('8 GB | 128 GB', '8 GB | 128 GB'), ('8 GB | 256 GB', '8 GB | 256 GB'), ('8 GB | 512 GB', '8 GB | 512 GB'), ('12 GB | 128 GB', '12 GB | 128 GB'), ('12 GB | 256 GB', '12 GB | 256 GB'), ('12 GB | 512 GB', '12 GB | 512 GB'), ('12 GB | 1 TB', '12 GB | 1 TB'), ('16 GB | 128 GB', '16 GB | 128 GB'), ('16 GB | 256 GB', '16 GB | 256 GB'), ('16 GB | 512 GB', '16 GB | 512 GB'), ('16 GB | 1 TB', '16 GB | 1 TB')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mobileproduct',
            name='os',
            field=models.CharField(blank=True, choices=[('Android', 'Android'), ('IOS', 'IOS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobileproduct',
            name='productPincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mobileproduct',
            name='sar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobileproduct',
            name='selfieCameraVideo',
            field=models.CharField(blank=True, choices=[('8k 30fps', '8k 30fps'), ('4k 120fps', '4k 120fps'), ('4k 60fps', '4k 60fps'), ('4k 30fps', '4k 30fps'), ('1080p 120fps', '1080p 120fps'), ('1080p 60fps', '1080p 60fps'), ('1080p 30fps', '1080p 30fps')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mobileproduct',
            name='simType',
            field=models.CharField(blank=True, choices=[('Single SIM (Nano-SIM)', 'Single SIM (Nano-SIM)'), ('Dual SIM (Nano-SIM, dual stand-by)', 'Dual SIM (Nano-SIM, dual stand-by)'), ('eSIM', 'eSIM'), ('Dual SIM + eSIM', 'Dual SIM + eSIM')], max_length=50, null=True),
        ),
    ]
